title: j3r3mias
author: Jeremias Gomes
email: j3r3miasmg@gmail.com

description: >-
    Random site.

baseurl: "/" # the subpath of your site, e.g. /blog
url: ""
twitter_username: j3r3m14s
github_username:  j3r3mias

markdown: kramdown

lsi: false
safe: true
incremental: false
highlighter: rouge

gist:
    noscript: false
    kramdown:
        math_engine: mathjax
        syntax_highlighter: rouge

defaults:
    - scope:
        path:           "radioamc/**"
        values:
            sitemap:    false
    - scope:
        path:           "payloads/**"
        values:
            sitemap:    false

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc

